name = "4ebi"
main = "index.js"
compatibility_date = "2025-11-09"
workers_dev = true
preview_urls = true
# logpush job is setup to capture from envs ending: log, pro, or one
logpush = false
# use node_compat or custom build
# node_compat = true
send_metrics = false
minify = false

[vars]
UUID = "9b89840c-47af-4e6e-94a9-1c134383d01b"
PROXYIP = "nima.nscl.ir"

# [build]
# command = "npm run deploy"

# [[rules]]
# type = "ESModule"
# globs = ["**/*.js"]
